name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # This gives read and write access to repository contents
      actions: read # This gives read access to actions and artifacts
      packages: write # This gives read and write access to packages

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "INSTALL_DIR=${GITHUB_WORKSPACE}/debug-container/vsdbg" >> $GITHUB_ENV
          echo "DOWNLOAD_DIR=${GITHUB_WORKSPACE}/downloads" >> $GITHUB_ENV

      - name: Print GitHub environment variables
        run: |
          echo "INSTALL_DIR": ${{ env.INSTALL_DIR }}
          echo "DOWNLOAD_DIR": ${{ env.DOWNLOAD_DIR }}
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Run Number: $GITHUB_RUN_NUMBER"
          echo "Job ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event Name: $GITHUB_EVENT_NAME"
          echo "Event Path: $GITHUB_EVENT_PATH"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "SHA: $GITHUB_SHA"
          echo "Ref: $GITHUB_REF"
          echo "Head Ref: $GITHUB_HEAD_REF"
          echo "Base Ref: $GITHUB_BASE_REF"

      - name: Create directories
        run: |
          mkdir -p ${{ env.INSTALL_DIR }}
          mkdir -p ${{ env.DOWNLOAD_DIR }}

      - name: Download and Extract vsdbg
        run: |
          curl -sSL -o ${{ env.DOWNLOAD_DIR }}/vsdbg.tar.gz https://vsdebugger.azureedge.net/vsdbg-17-11-10506-2/vsdbg-linux-x64.tar.gz &&
          tar -xzf ${{ env.DOWNLOAD_DIR }}/vsdbg.tar.gz -C ${{ env.INSTALL_DIR }} &&
          ls -l ${{ env.INSTALL_DIR }}

      - name: ls and pwd
        run: |
          pwd &&
          ls -la

      - name: Build the Docker image
        run: docker build . --file ./debug-container/Dockerfile.base.ubuntu.22.04.amd64 --tag aspnet6-debug-ubuntu-amd64:master_$GITHUB_RUN_ID
