name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # This gives read and write access to repository contents
      actions: read # This gives read access to actions and artifacts
      packages: write # This gives read and write access to packages

    steps:
      - uses: actions/checkout@v4

      - name: run('pwd')
        run: pwd

      - name: run('ls -la')
        run: ls -la

      # - name: Print GitHub environment variables
      #   run: |
      #     echo "Workflow: $GITHUB_WORKFLOW"
      #     echo "Run ID: $GITHUB_RUN_ID"
      #     echo "Run Number: $GITHUB_RUN_NUMBER"
      #     echo "Job ID: $GITHUB_JOB"
      #     echo "Action: $GITHUB_ACTION"
      #     echo "Actor: $GITHUB_ACTOR"
      #     echo "Repository: $GITHUB_REPOSITORY"
      #     echo "Event Name: $GITHUB_EVENT_NAME"
      #     echo "Event Path: $GITHUB_EVENT_PATH"
      #     echo "Workspace: $GITHUB_WORKSPACE"
      #     echo "SHA: $GITHUB_SHA"
      #     echo "Ref: $GITHUB_REF"
      #     echo "Head Ref: $GITHUB_HEAD_REF"
      #     echo "Base Ref: $GITHUB_BASE_REF"

      - name: Set up environment
        run: |
          echo "INSTALL_DIR=$GITHUB_WORKSPACE/vsdbg" >> $GITHUB_ENV &&
          echo "DOWNLOAD_DIR=$GITHUB_WORKSPACE/downloads" >> $GITHUB_ENV &&

      - name: Download and Extract vsdbg
        run: |
          mkdir -p ${{ env.DOWNLOAD_DIR }} &&
          curl -sSL -o ${{ env.DOWNLOAD_DIR }}/vsdbg.tar.gz https://vsdebugger.azureedge.net/vsdbg-17-11-10506-2/vsdbg-linux-x64.tar.gz &&
          tar -xzf ${{ env.DOWNLOAD_DIR }}/vsdbg.tar.gz -C ${{ env.DOWNLOAD_DIR }} &&
          ls -l ${{ env.DOWNLOAD_DIR }}

      # - name: create dir for vsdbg
      #   run: mkdir -p $GITHUB_WORKSPACE/vsdbg
      # - name: Build the Docker image
      #   run: docker build . --file ./debug-container/Dockerfile.base.ubuntu.22.04.amd64 --tag aspnet6-debug-ubuntu-amd64:master_$(date +%s)

      - name: Install vsdbg
        run: |
          INSTALL_DIR=$GITHUB_WORKSPACE/vsdbg
          sudo mkdir -p ${INSTALL_DIR}
          RETRIES=5
          DOWNLOAD_URL="https://aka.ms/getvsdbgsh"
          for i in $(seq 1 $RETRIES); do
            sudo curl -sSL $DOWNLOAD_URL | bash /dev/stdin -v latest -l ${INSTALL_DIR} && break || sleep 15
            if [ $i -eq $RETRIES ]; then
              echo "ERROR: Failed to download vsdbg after $RETRIES attempts"
              exit 1
            fi
          done
