name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: run('pwd')
        run: pwd

      - name: run('ls -la')
        run: ls -la

      # - name: Build the Docker image
      #   run: docker build . --file ./debug-container/Dockerfile.base.ubuntu.22.04.amd64 --tag aspnet6-debug-ubuntu-amd64:master_$(date +%s)

      - name: Install vsdbg
        run: |
          INSTALL_DIR=/vsdbg
          mkdir -p ${INSTALL_DIR}
          RETRIES=5
          DOWNLOAD_URL="https://aka.ms/getvsdbgsh"
          for i in $(seq 1 $RETRIES); do
            curl -sSL $DOWNLOAD_URL | bash /dev/stdin -v latest -l ${INSTALL_DIR} && break || sleep 15
            if [ $i -eq $RETRIES ]; then
              echo "ERROR: Failed to download vsdbg after $RETRIES attempts"
              exit 1
            fi
          done
